[build]
  command = "npm run build" # or "npm run deploy" depending on your setup
  publish = "public" # specify your folder with front-end files

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
